# vim:fileencoding=utf-8:foldmethod=marker

# kitty.conf

## Theme
include themes/Modus_Vivendi.conf

## Font
font_family Iosevka Nerd Font Mono
font_size   13

## Cursor
cursor_shape                 block
cursor_blink_interval        0
cursor_trail                 1
cursor_trail_decay           0.01 0.5
cursor_trail_start_threshold 0

## Scrollback
scrollback_lines 10000

## Mouse
mouse_hide_wait 3
url_style       curly
url_prefixes    file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh
detect_urls     yes

## Bell
enable_audio_bell no

## Tab
tab_bar_style       powerline
tab_bar_min_tabs    1
tab_powerline_style slanted
tab_title_template  "{title or tab.active_wd}"

## Shell
shell             /opt/homebrew/bin/fish
shell_integration no-cursor

## Shortcuts

### Modifier
kitty_mod opt+shift

### Cursor
map cmd+backspace send_text all \x15
#                               ctrl+u erase_line

### Scroll
map kitty_mod+up       scroll_line_up
map kitty_mod+down     scroll_line_down
map kitty_mod+left     scroll_page_up
map kitty_mod+right    scroll_page_down
map kitty_mod+cmd+up   scroll_home
map kitty_mod+cmd+down scroll_end

### Tab
map kitty_mod+t new_tab
map kitty_mod+w close_tab
map kitty_mod+o previous_tab
map kitty_mod+p next_tab
map kitty_mod+, set_tab_title
map kitty_mod+g new_tab_with_cwd

### Window
map kitty_mod+enter new_window
map kitty_mod+\     close_window
map kitty_mod+[     previous_window
map kitty_mod+]     next_window
map kitty_mod+l     next_layout
map kitty_mod+n     new_os_window
